INTRODUCTION TO NUMPY:

In [1]:
import numpy as np
import os

In [2]:
a=np.arange(8)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

Vectors,The 1D Arrays:

In [4]:
a = np.array([1.,2.,3.,])

In [5]:
a

array([1., 2., 3.])

In [6]:

b=np.zeros(3,int)

In [7]:
b

array([0, 0, 0])

In [8]:
print(a)

[1. 2. 3.]


In [9]:
np.zeros_like(a)

array([0., 0., 0.])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones_like(a)

array([1., 1., 1.])

In [12]:
np.empty(2)

array([-5.48749279e-289, -6.00056772e-289])

In [13]:
np.full(4,7)

array([7, 7, 7, 7])

In [14]:
np.arange(3,6)

array([3, 4, 5])

In [15]:
np.arange(2,4,6)

array([2])

GENERATING RANDOM NUMBERS:

In [16]:
np.random.randint(0,3,5)

array([1, 2, 0, 1, 1], dtype=int32)

In [17]:
np.random.rand(6)

array([0.38298383, 0.74479881, 0.98509248, 0.07597351, 0.22722276,
       0.901218  ])

In [18]:
np.random.uniform(1,20,3)

array([ 8.16908355,  2.28322166, 16.85398979])

In [19]:
np.random.randn(7)

array([ 1.33986338,  1.09827957,  0.06511343, -0.00254524,  0.55457107,
        0.9918384 ,  0.72090111])

In [20]:
np.random.normal(7,3,4)

array([ 8.48094455,  6.1923829 , 11.49818329, 11.38638569])

In [21]:
rng=np.random.default_rng()

In [22]:
rng.integers(0,10,2)

array([4, 5])

In [23]:
rng.random(3)

array([0.85281365, 0.90072974, 0.53887477])

In [24]:
rng.integers(0,10,3,endpoint=True)

array([5, 4, 2])

In [25]:
a=np.arange(1,7)

In [26]:
a

array([1, 2, 3, 4, 5, 6])

In [27]:
a[1]

np.int64(2)

In [28]:
a[2:4]

array([3, 4])

In [29]:
a[-3:]

array([4, 5, 6])

In [30]:
a[::3]

array([1, 4])

In [31]:
a[[2,4,5]]

array([3, 5, 6])

In [32]:
a[3]=0

In [33]:
a

array([1, 2, 3, 0, 5, 6])

In [34]:
s=(1,2,3,4,5,6,7,6,5,4,3,2,1)

In [35]:
np.any(a>5)

np.True_

In [36]:
np.all(a<5)

np.False_

In [37]:
np.clip(a,3,1)

array([1, 1, 1, 1, 1, 1])

In [38]:
np.sqrt(67)

np.float64(8.18535277187245)

In [39]:
np.sqrt(2)

np.float64(1.4142135623730951)

In [40]:
np.exp(2)

np.float64(7.38905609893065)

In [41]:
np.log(5)

np.float64(1.6094379124341003)

In [42]:
np.log(10)

np.float64(2.302585092994046)

In [43]:
d=np.array([[1,2,3,4],[4,6,7,8]])

In [44]:
d

array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [45]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [47]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
d[0,2]

np.int64(3)

In [51]:
d[1,:]

array([4, 6, 7, 8])

In [52]:
d.sum()

np.int64(35)

In [53]:
d.sum(axis=1)

array([10, 25])

MATRIX ARITHMETIC

In [54]:
d.min()

np.int64(1)

In [57]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
d.ndim==3

False

In [67]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])